/* css*/
import styles from './Brands.module.scss';

function VeganWay() {
  return (
    <>
      <img
        className={`${styles.img_main} ${styles.img_main_veganway}`}
        src="https://veganway.com.br/wp-content/uploads/2022/09/header-post.jpg"
        alt=""
      />
      <img
        className={styles.img_products}
        src="https://veganway.com.br/wp-content/uploads/2021/07/FUSION-PROTEIN-BAUNILHA-VEGANWAY.jpg"
        alt=""
      />
      <img
        className={styles.img_products}
        src="https://veganway.com.br/wp-content/uploads/2021/07/FUSION-PROTEIN-CACAU-VEGANWAY.jpg"
        alt=""
      />
      <img
        className={styles.img_products}
        src="https://veganway.com.br/wp-content/uploads/2021/07/FUSION-PROTEIN-NATURAL-VEGANWAY.jpg"
        alt=""
      />
      <img
        className={styles.img_products}
        src="https://veganway.com.br/wp-content/uploads/2021/07/PROTEINA-DE-ARROZ-RICE-PROTEIN-CACAU-VEGANWAY-p.jpg"
        alt=""
      />
      <img
        className={styles.img_products}
        src="https://veganway.com.br/wp-content/uploads/2021/07/PROTEINA-DE-ARROZ-RICE-PROTEIN-NATURAL-VEGANWAY.jpg"
        alt=""
      />
      <img
        className={styles.img_products}
        src="https://veganway.com.br/wp-content/uploads/2021/07/PROTEINA-DE-ARROZ-RICE-PROTEIN-MORANGO-VEGANWAY.jpg"
        alt=""
      />
      <img
        className={styles.img_products}
        src="https://veganway.com.br/wp-content/uploads/2021/07/PEA-PROTEIN-CACAU-COM-MORANGO-VEGANWAY.jpg"
        alt=""
      />
      <img
        className={styles.img_products}
        src="https://veganway.com.br/wp-content/uploads/2021/07/PEA-PROTEIN-BAUNILHA-VEGANWAY.jpg"
        alt=""
      />
      <img
        className={styles.img_products}
        src="https://veganway.com.br/wp-content/uploads/2021/07/PEA-PROTEIN-NATURAL-VEGANWAY.jpg"
        alt=""
      />
      <img
        className={styles.img_products}
        src="https://veganway.com.br/wp-content/uploads/2021/07/PEAT.jpg"
        alt=""
      />
      <img
        className={styles.img_products}
        src="https://veganway.com.br/wp-content/uploads/2020/07/LEVEDURA-NUTRICIONAL-NOVO-NATURAL-VEGANWAY-1.jpg"
        alt=""
      />
      <img
        className={styles.img_products}
        src="https://veganway.com.br/wp-content/uploads/2022/04/LEVEDURA-NUTRICIONAL-SPECIAL-POWDER-VEGANWAY.jpg"
        alt=""
      />
      <img
        className={styles.img_products}
        src="https://veganway.com.br/wp-content/uploads/2021/08/LEVEDURA-NUTRICIONAL-PROVOLONE-VEGANWAY.jpg"
        alt=""
      />
      <img
        className={styles.img_products}
        src="https://veganway.com.br/wp-content/uploads/2020/07/LEVEDURA-NUTRICIONAL-NOVO-MANTEIGA-VEGANWAY.jpg"
        alt=""
      />
      <img
        className={styles.img_products}
        src="https://veganway.com.br/wp-content/uploads/2020/07/LEVEDURA-NUTRICIONAL-NOVO-COSTELA-VEGANWAY.jpg"
        alt=""
      />
      <img
        className={styles.img_products}
        src="https://veganway.com.br/wp-content/uploads/2020/07/LEVEDURA-NUTRICIONAL-NOVOI-ALECRIM-VEGANWAY.jpg"
        alt=""
      />
      <img
        className={styles.img_products}
        src="https://veganway.com.br/wp-content/uploads/2021/07/flakes-100g2-1.jpg"
        alt=""
      />
      <img
        className={styles.img_products}
        src="https://veganway.com.br/wp-content/uploads/2021/07/capsulas-metil-b12.jpg"
        alt=""
      />
      <img
        className={styles.img_products}
        src="https://veganway.com.br/wp-content/uploads/2021/07/capsulas-D3.jpg"
        alt=""
      />
      <img
        className={styles.img_products}
        src="https://veganway.com.br/wp-content/uploads/2021/07/capsulas-vitac.jpg"
        alt=""
      />
      <img
        className={styles.img_products}
        src="https://veganway.com.br/wp-content/uploads/2021/07/capsulas-triptonfano.jpg"
        alt=""
      />
      <img
        className={styles.img_products}
        src="https://veganway.com.br/wp-content/uploads/2021/07/PALATINOSE-VEGANWAY-1.jpg"
        alt=""
      />
      <img
        className={styles.img_products}
        src="https://veganway.com.br/wp-content/uploads/2021/07/imagem-site.jpg"
        alt=""
      />
      <img
        className={styles.img_products}
        src="https://veganway.com.br/wp-content/uploads/2021/07/Glutamina-1.png"
        alt=""
      />
      <img
        className={styles.img_products}
        src="https://veganway.com.br/wp-content/uploads/2021/07/GLUTAIMUNE-SHOT-IMUNIDADE.jpg"
        alt=""
      />
      <img
        className={styles.img_products}
        src="https://veganway.com.br/wp-content/uploads/2021/07/termogenico-natural-thermoC210.jpg"
        alt=""
      />
      <img
        className={styles.img_products}
        src="https://veganway.com.br/wp-content/uploads/2021/07/CREATINE-SITE.jpg"
        alt=""
      />
      <img className={styles.img_products} src="" alt="" />
      <img className={styles.img_products} src="" alt="" />
    </>
  );
}

export default VeganWay;
